driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: create
    run_list:
      - recipe[test::create]
  - name: create_thin
    excludes:
    - centos-5.11
    - debian-7.11
    - ubuntu-12.04
    run_list:
      - recipe[test::create_thin]
  - name: resize
    run_list:
      - recipe[test::create]
      - recipe[test::resize]
  - name: resize_thin
    excludes:
    - centos-5.11
    - debian-7.11
    - ubuntu-12.04
    run_list:
      - recipe[test::create_thin]
      - recipe[test::resize_thin]
